# Generated by Django 4.1.7 on 2023-04-02 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_list_board_delete_board'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='list',
            options={'ordering': ['created_at']},
        ),
        migrations.AddField(
            model_name='card',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
